# Preliminary operations

In [ ]:
# import main libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from collections import defaultdict
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [ ]:
# mont Google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# import training data
df_data_train = pd.read_excel("drive/MyDrive/Progetto Data Mining 2/CODICE PROGETTO/Outliers/DATASET NO OUTLIERS/df_prep_TRAIN_no_outliers.xlsx", index_col="Unnamed: 0")

# get training values
X_train = df_data_train.drop(labels = ["std", "mfcc_kur", "mfcc_kur_w2"], axis=1).values
y_train = df_data_train.loc[:, ["std", "mfcc_kur", "mfcc_kur_w2"]]

# import test data
df_data_test = pd.read_excel("drive/MyDrive/Progetto Data Mining 2/CODICE PROGETTO/Outliers/DATASET NO OUTLIERS/df_prep_TEST_no_outliers.xlsx", index_col="Unnamed: 0")

# get test values
X_test = df_data_test.drop(labels = ["std", "mfcc_kur", "mfcc_kur_w2"], axis=1).values
y_test = df_data_test.loc[:, ["std", "mfcc_kur", "mfcc_kur_w2"]]


#Hyperparameter Tuning

In [ ]:
reg = RandomForestRegressor()

parameters = {
    "n_estimators": [10, 100, 1000]
}

In [ ]:
RSKF = KFold(
    n_splits=10
)

grid = RandomizedSearchCV(
    reg,
    n_iter=3,
    param_distributions = parameters,
    cv=RSKF,
    n_jobs = -1,
    refit = True,
    verbose=2,
    random_state=0
)
  
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 10 folds for each of 3 candidates, totalling 30 fits


RandomizedSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
                   estimator=RandomForestRegressor(), n_iter=3, n_jobs=-1,
                   param_distributions={'n_estimators': [10, 100, 1000]},
                   random_state=0, verbose=2)

In [ ]:
grid.best_params_

{'n_estimators': 1000}

In [ ]:
grid_scores = pd.DataFrame(grid.cv_results_)
grid_scores

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       1.182081      0.251347         0.004823        0.002145   
1      11.664843      0.861146         0.020769        0.008911   
2     115.691332      0.426941         0.148414        0.018389   

  param_n_estimators                  params  split0_test_score  \
0                 10    {'n_estimators': 10}           0.789199   
1                100   {'n_estimators': 100}           0.815887   
2               1000  {'n_estimators': 1000}           0.815751   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.716139           0.703663           0.743259           0.589651   
1           0.738058           0.719790           0.756118           0.645175   
2           0.743647           0.730390           0.762992           0.653618   

   split5_test_score  split6_test_score  split7_test_score  split8_test_score  \
0           0.633610           0.816948           0.684912           0.732145   
1           0.643169           0.849443           0.710313           0.789417   
2           0.646654           0.860334           0.723231           0.801298   

   split9_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.622224         0.703175        0.068973                3  
1           0.696509         0.736388        0.064700                2  
2           0.703259         0.744117        0.064998                1

In [ ]:
grid_scores.to_excel("tuning_scores_RandomForest_reg.xlsx")

# Random Forest Regressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
regr = RandomForestRegressor(random_state=0,
                             n_estimators=1000,
                             criterion='squared_error'
                             )
regr.fit(X_train, y_train)

regr.score(X_test, y_test)

[[-1.28746807 -1.24215721  0.35592491]
 [-1.22138358 -1.04133056  0.51532899]
 [-1.14433594 -0.92408096  0.60430679]
 ...
 [ 1.11776651  1.36908567 -0.52819897]
 [ 1.4125422   1.3332668  -0.91343888]
 [ 1.08609757  1.18430091 -0.94504768]]


0.7332430818221436

In [ ]:
y_pred = regr.predict(X_test)

In [ ]:
print(r2_score(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))

0.7332430818221436
0.3738869633131627
0.2583099810907743


In [21]:
print(r2_score(y_test, y_pred, multioutput='raw_values'))
print(mean_absolute_error(y_test, y_pred, multioutput='raw_values'))
print(mean_squared_error(y_test, y_pred, multioutput='raw_values'))

[0.73037445 0.70035739 0.76899741]
[0.37717115 0.37321306 0.37127668]
[0.24722317 0.29275587 0.2349509 ]
